import type { SkillNode } from '../types.js';

export const SKILL_FAMILIES: { id: string; name: string; nameAr: string }[] = [
  { id: 'pull-up', name: 'Pull-up & Weighted Pull-up', nameAr: 'السحب والسحب بالوزن' },
  { id: 'muscle-up', name: 'Muscle-up', nameAr: 'العضلة العكسية' },
  { id: 'handstand', name: 'Handstand & HSPU', nameAr: 'الوقوف على اليدين والدفع' },
  { id: 'ring-push-up', name: 'Ring Push-up', nameAr: 'الضغط بالحلقات' },
  { id: 'pistol', name: 'Pistol Squat', nameAr: 'القرفصاء برجل واحدة' },
  { id: 'front-lever', name: 'Front Lever', nameAr: 'الرافعة الأمامية' },
  { id: 'back-lever', name: 'Back Lever', nameAr: 'الرافعة الخلفية' },
  { id: 'planche', name: 'Planche', nameAr: 'البلانش' },
  { id: 'l-sit', name: 'L-sit & Compression', nameAr: 'الجلوس L والانضغاط' },
  { id: 'expert-rings', name: 'Expert Ring Branches', nameAr: 'فروع الحلقات المتقدمة' }
];

const q = {
  beginner: { requiredExposures: 3, requiredSuccessfulExposures: 2, minQuality: 0.7, requiresVideo: false, requiresCoach: false, expertLocked: false },
  intermediate: { requiredExposures: 3, requiredSuccessfulExposures: 2, minQuality: 0.75, requiresVideo: false, requiresCoach: false, expertLocked: false },
  advanced: { requiredExposures: 3, requiredSuccessfulExposures: 2, minQuality: 0.75, requiresVideo: true, requiresCoach: false, expertLocked: false },
  expert: { requiredExposures: 6, requiredSuccessfulExposures: 5, minQuality: 0.85, requiresVideo: true, requiresCoach: true, expertLocked: true }
};

export const SKILL_NODES: SkillNode[] = [
  // Pull-up tree
  { id: 'passive-hang', familyId: 'pull-up', name: 'Passive Hang', nameAr: 'تعليق سلبي', stage: 1, difficulty: 'fundamental', apparatus: ['pull-up-bar'], staticOrDynamic: 'static', bentOrStraightArm: 'straight', role: 'technique', riskLevel: 'low', targetDose: { sets: 3, holdSecondsMin: 20, holdSecondsMax: 30 }, targetQuality: 0.7, unlockRule: q.beginner, regressRule: { failedExposures: 3, minQuality: 0.7, painBlocks: true }, volumeRule: 'TECHNIQUE_NO_VOLUME', prerequisites: [], progressions: ['active-hang'], regressions: [], replacementCandidates: [] },
  { id: 'active-hang', familyId: 'pull-up', name: 'Active Hang', nameAr: 'تعليق نشط', stage: 2, difficulty: 'fundamental', apparatus: ['pull-up-bar'], staticOrDynamic: 'static', bentOrStraightArm: 'straight', role: 'technique', riskLevel: 'low', targetDose: { sets: 3, holdSecondsMin: 15, holdSecondsMax: 30 }, targetQuality: 0.7, unlockRule: q.beginner, regressRule: { failedExposures: 3, minQuality: 0.7, painBlocks: true }, volumeRule: 'TECHNIQUE_NO_VOLUME', prerequisites: ['passive-hang'], progressions: ['scapular-pull-up'], regressions: ['passive-hang'], replacementCandidates: [] },
  { id: 'scapular-pull-up', familyId: 'pull-up', name: 'Scapular Pull-up', nameAr: 'سحب كتفي', stage: 3, difficulty: 'fundamental', apparatus: ['pull-up-bar'], staticOrDynamic: 'dynamic', bentOrStraightArm: 'bent', role: 'technique', riskLevel: 'low', targetDose: { sets: 3, repsMin: 5, repsMax: 8 }, targetQuality: 0.7, unlockRule: q.beginner, regressRule: { failedExposures: 3, minQuality: 0.7, painBlocks: true }, volumeRule: 'TECHNIQUE_NO_VOLUME', prerequisites: ['active-hang'], progressions: ['assisted-pull-up'], regressions: ['active-hang'], replacementCandidates: [] },
  { id: 'assisted-pull-up', familyId: 'pull-up', name: 'Assisted Pull-up', nameAr: 'سحب مساعد', stage: 4, difficulty: 'beginner', apparatus: ['pull-up-bar', 'bands'], staticOrDynamic: 'dynamic', bentOrStraightArm: 'bent', role: 'skill', riskLevel: 'low', targetDose: { sets: 3, repsMin: 4, repsMax: 6 }, targetQuality: 0.7, unlockRule: q.beginner, regressRule: { failedExposures: 3, minQuality: 0.7, painBlocks: true }, volumeRule: 'DYNAMIC_FULL_SET', prerequisites: ['scapular-pull-up'], progressions: ['strict-chin-up'], regressions: ['scapular-pull-up'], replacementCandidates: ['pulldown'] },
  { id: 'strict-chin-up', familyId: 'pull-up', name: 'Strict Chin-up', nameAr: 'سحب ذقن صارم', stage: 5, difficulty: 'beginner', apparatus: ['pull-up-bar'], staticOrDynamic: 'dynamic', bentOrStraightArm: 'bent', role: 'skill', riskLevel: 'low', targetDose: { sets: 3, repsMin: 4, repsMax: 6 }, targetQuality: 0.75, unlockRule: q.intermediate, regressRule: { failedExposures: 3, minQuality: 0.75, painBlocks: true }, volumeRule: 'DYNAMIC_FULL_SET', prerequisites: ['assisted-pull-up'], progressions: ['strict-pull-up'], regressions: ['assisted-pull-up'], replacementCandidates: ['pulldown'] },
  { id: 'strict-pull-up', familyId: 'pull-up', name: 'Strict Pull-up', nameAr: 'سحب صارم', stage: 6, difficulty: 'intermediate', apparatus: ['pull-up-bar'], staticOrDynamic: 'dynamic', bentOrStraightArm: 'bent', role: 'strength', riskLevel: 'medium', targetDose: { sets: 3, repsMin: 4, repsMax: 6 }, targetQuality: 0.75, unlockRule: q.intermediate, regressRule: { failedExposures: 3, minQuality: 0.75, painBlocks: true }, volumeRule: 'DYNAMIC_FULL_SET', prerequisites: ['strict-chin-up'], progressions: ['weighted-pull-up', 'chest-to-bar-pull-up'], regressions: ['strict-chin-up'], replacementCandidates: ['pulldown'] },
  { id: 'weighted-pull-up', familyId: 'pull-up', name: 'Weighted Pull-up', nameAr: 'سحب مع وزن', stage: 7, difficulty: 'advanced', apparatus: ['pull-up-bar', 'dip-belt', 'plates'], staticOrDynamic: 'dynamic', bentOrStraightArm: 'bent', role: 'strength', riskLevel: 'medium', targetDose: { sets: 3, repsMin: 4, repsMax: 6 }, targetQuality: 0.75, unlockRule: q.intermediate, regressRule: { failedExposures: 3, minQuality: 0.75, painBlocks: true }, volumeRule: 'WEIGHTED_DYNAMIC_FULL_SET', prerequisites: ['strict-pull-up'], progressions: ['heavy-weighted-pull-up', 'muscle-up'], regressions: ['strict-pull-up'], replacementCandidates: ['pulldown'] },
  { id: 'heavy-weighted-pull-up', familyId: 'pull-up', name: 'Heavy Weighted Pull-up', nameAr: 'سحب ثقيل مع وزن', stage: 8, difficulty: 'advanced', apparatus: ['pull-up-bar', 'dip-belt', 'plates'], staticOrDynamic: 'dynamic', bentOrStraightArm: 'bent', role: 'strength', riskLevel: 'medium', targetDose: { sets: 3, repsMin: 3, repsMax: 5 }, targetQuality: 0.8, unlockRule: q.advanced, regressRule: { failedExposures: 3, minQuality: 0.8, painBlocks: true }, volumeRule: 'WEIGHTED_DYNAMIC_FULL_SET', prerequisites: ['weighted-pull-up'], progressions: ['one-arm-pull-up'], regressions: ['weighted-pull-up'], replacementCandidates: ['pulldown'] },
  { id: 'chest-to-bar-pull-up', familyId: 'pull-up', name: 'Chest-to-bar Pull-up', nameAr: 'سحب صدر للبار', stage: 7, difficulty: 'advanced', apparatus: ['pull-up-bar'], staticOrDynamic: 'dynamic', bentOrStraightArm: 'bent', role: 'skill', riskLevel: 'medium', targetDose: { sets: 3, repsMin: 3, repsMax: 5 }, targetQuality: 0.8, unlockRule: q.advanced, regressRule: { failedExposures: 3, minQuality: 0.8, painBlocks: true }, volumeRule: 'DYNAMIC_FULL_SET', prerequisites: ['strict-pull-up'], progressions: ['explosive-high-pull'], regressions: ['strict-pull-up'], replacementCandidates: ['pulldown'] },
  { id: 'explosive-high-pull', familyId: 'pull-up', name: 'Explosive High Pull', nameAr: 'سحب عالي انفجاري', stage: 8, difficulty: 'advanced', apparatus: ['pull-up-bar'], staticOrDynamic: 'dynamic', bentOrStraightArm: 'bent', role: 'skill', riskLevel: 'high', targetDose: { sets: 4, repsMin: 2, repsMax: 4 }, targetQuality: 0.8, unlockRule: q.advanced, regressRule: { failedExposures: 3, minQuality: 0.8, painBlocks: true }, volumeRule: 'DYNAMIC_FULL_SET', prerequisites: ['chest-to-bar-pull-up'], progressions: ['muscle-up'], regressions: ['chest-to-bar-pull-up'], replacementCandidates: ['pulldown'] },
  { id: 'one-arm-pull-up', familyId: 'pull-up', name: 'One-arm Pull-up', nameAr: 'سحب بذراع واحدة', stage: 9, difficulty: 'expert', apparatus: ['pull-up-bar'], staticOrDynamic: 'dynamic', bentOrStraightArm: 'bent', role: 'skill', riskLevel: 'expert', targetDose: { sets: 4, repsMin: 1, repsMax: 3 }, targetQuality: 0.85, unlockRule: q.expert, regressRule: { failedExposures: 3, minQuality: 0.85, painBlocks: true }, volumeRule: 'WEIGHTED_DYNAMIC_FULL_SET', prerequisites: ['heavy-weighted-pull-up'], progressions: [], regressions: ['heavy-weighted-pull-up'], replacementCandidates: [] },

  // Muscle-up tree
  { id: 'straight-bar-support', familyId: 'muscle-up', name: 'Straight-bar Support', nameAr: 'دعم البار المستقيم', stage: 1, difficulty: 'beginner', apparatus: ['pull-up-bar'], staticOrDynamic: 'static', bentOrStraightArm: 'straight', role: 'technique', riskLevel: 'low', targetDose: { sets: 3, holdSecondsMin: 15, holdSecondsMax: 30 }, targetQuality: 0.7, unlockRule: q.beginner, regressRule: { failedExposures: 3, minQuality: 0.7, painBlocks: true }, volumeRule: 'TECHNIQUE_NO_VOLUME', prerequisites: ['active-hang'], progressions: ['straight-bar-dip'], regressions: [], replacementCandidates: [] },
  { id: 'straight-bar-dip', familyId: 'muscle-up', name: 'Straight-bar Dip', nameAr: 'غطس بالبار المستقيم', stage: 2, difficulty: 'intermediate', apparatus: ['pull-up-bar'], staticOrDynamic: 'dynamic', bentOrStraightArm: 'bent', role: 'skill', riskLevel: 'medium', targetDose: { sets: 3, repsMin: 4, repsMax: 6 }, targetQuality: 0.75, unlockRule: q.intermediate, regressRule: { failedExposures: 3, minQuality: 0.75, painBlocks: true }, volumeRule: 'DYNAMIC_FULL_SET', prerequisites: ['straight-bar-support'], progressions: ['low-bar-transition'], regressions: ['straight-bar-support'], replacementCandidates: [] },
  { id: 'low-bar-transition', familyId: 'muscle-up', name: 'Low-bar Transition', nameAr: 'انتقال البار المنخفض', stage: 3, difficulty: 'intermediate', apparatus: ['pull-up-bar'], staticOrDynamic: 'dynamic', bentOrStraightArm: 'bent', role: 'skill', riskLevel: 'medium', targetDose: { sets: 4, repsMin: 2, repsMax: 4 }, targetQuality: 0.75, unlockRule: q.intermediate, regressRule: { failedExposures: 3, minQuality: 0.75, painBlocks: true }, volumeRule: 'TECHNIQUE_NO_VOLUME', prerequisites: ['straight-bar-dip'], progressions: ['band-assisted-muscle-up'], regressions: ['straight-bar-dip'], replacementCandidates: [] },
  { id: 'band-assisted-muscle-up', familyId: 'muscle-up', name: 'Band-assisted Muscle-up', nameAr: 'عضلة عكسية مساعدة', stage: 4, difficulty: 'advanced', apparatus: ['pull-up-bar', 'bands'], staticOrDynamic: 'dynamic', bentOrStraightArm: 'bent', role: 'skill', riskLevel: 'high', targetDose: { sets: 4, repsMin: 1, repsMax: 3 }, targetQuality: 0.8, unlockRule: q.advanced, regressRule: { failedExposures: 3, minQuality: 0.8, painBlocks: true }, volumeRule: 'DYNAMIC_FULL_SET', prerequisites: ['low-bar-transition', 'explosive-high-pull'], progressions: ['strict-bar-muscle-up'], regressions: ['low-bar-transition'], replacementCandidates: [] },
  { id: 'strict-bar-muscle-up', familyId: 'muscle-up', name: 'Strict Bar Muscle-up', nameAr: 'عضلة عكسية صارمة', stage: 5, difficulty: 'advanced', apparatus: ['pull-up-bar'], staticOrDynamic: 'dynamic', bentOrStraightArm: 'bent', role: 'skill', riskLevel: 'high', targetDose: { sets: 4, repsMin: 1, repsMax: 3 }, targetQuality: 0.8, unlockRule: q.advanced, regressRule: { failedExposures: 3, minQuality: 0.8, painBlocks: true }, volumeRule: 'DYNAMIC_FULL_SET', prerequisites: ['band-assisted-muscle-up'], progressions: ['ring-muscle-up', 'weighted-muscle-up'], regressions: ['band-assisted-muscle-up'], replacementCandidates: [] },
  { id: 'ring-muscle-up', familyId: 'muscle-up', name: 'Strict Ring Muscle-up', nameAr: 'عضلة عكسية بالحلقات', stage: 6, difficulty: 'advanced', apparatus: ['rings'], staticOrDynamic: 'dynamic', bentOrStraightArm: 'bent', role: 'skill', riskLevel: 'high', targetDose: { sets: 4, repsMin: 1, repsMax: 3 }, targetQuality: 0.8, unlockRule: q.advanced, regressRule: { failedExposures: 3, minQuality: 0.8, painBlocks: true }, volumeRule: 'DYNAMIC_FULL_SET', prerequisites: ['strict-bar-muscle-up'], progressions: ['weighted-muscle-up'], regressions: ['strict-bar-muscle-up'], replacementCandidates: [] },
  { id: 'weighted-muscle-up', familyId: 'muscle-up', name: 'Weighted Muscle-up', nameAr: 'عضلة عكسية مع وزن', stage: 7, difficulty: 'expert', apparatus: ['pull-up-bar', 'dip-belt', 'plates'], staticOrDynamic: 'dynamic', bentOrStraightArm: 'bent', role: 'strength', riskLevel: 'expert', targetDose: { sets: 4, repsMin: 1, repsMax: 3 }, targetQuality: 0.85, unlockRule: q.expert, regressRule: { failedExposures: 3, minQuality: 0.85, painBlocks: true }, volumeRule: 'WEIGHTED_DYNAMIC_FULL_SET', prerequisites: ['strict-bar-muscle-up'], progressions: [], regressions: ['strict-bar-muscle-up'], replacementCandidates: [] },

  // Handstand tree
  { id: 'wrist-prep', familyId: 'handstand', name: 'Wrist Preparation', nameAr: 'إعداد المعصم', stage: 1, difficulty: 'fundamental', apparatus: ['floor'], staticOrDynamic: 'static', bentOrStraightArm: 'straight', role: 'technique', riskLevel: 'low', targetDose: { sets: 1, holdSecondsMin: 180, holdSecondsMax: 300 }, targetQuality: 0.7, unlockRule: q.beginner, regressRule: { failedExposures: 3, minQuality: 0.7, painBlocks: true }, volumeRule: 'TECHNIQUE_NO_VOLUME', prerequisites: [], progressions: ['wall-plank'], regressions: [], replacementCandidates: [] },
  { id: 'wall-plank', familyId: 'handstand', name: 'Wall Plank', nameAr: 'لوح بالجدار', stage: 2, difficulty: 'fundamental', apparatus: ['wall'], staticOrDynamic: 'static', bentOrStraightArm: 'straight', role: 'technique', riskLevel: 'low', targetDose: { sets: 3, holdSecondsMin: 20, holdSecondsMax: 45 }, targetQuality: 0.7, unlockRule: q.beginner, regressRule: { failedExposures: 3, minQuality: 0.7, painBlocks: true }, volumeRule: 'TECHNIQUE_NO_VOLUME', prerequisites: ['wrist-prep'], progressions: ['wall-walk'], regressions: ['wrist-prep'], replacementCandidates: [] },
  { id: 'wall-walk', familyId: 'handstand', name: 'Wall Walk', nameAr: 'مشي بالجدار', stage: 3, difficulty: 'beginner', apparatus: ['wall'], staticOrDynamic: 'dynamic', bentOrStraightArm: 'straight', role: 'technique', riskLevel: 'low', targetDose: { sets: 3, repsMin: 3, repsMax: 5 }, targetQuality: 0.7, unlockRule: q.beginner, regressRule: { failedExposures: 3, minQuality: 0.7, painBlocks: true }, volumeRule: 'TECHNIQUE_NO_VOLUME', prerequisites: ['wall-plank'], progressions: ['handstand-wall'], regressions: ['wall-plank'], replacementCandidates: [] },
  { id: 'handstand-wall', familyId: 'handstand', name: 'Chest-to-wall Handstand', nameAr: 'وقوف على اليدين بالجدار', stage: 4, difficulty: 'intermediate', apparatus: ['wall'], staticOrDynamic: 'static', bentOrStraightArm: 'straight', role: 'technique', riskLevel: 'medium', targetDose: { sets: 5, holdSecondsMin: 20, holdSecondsMax: 45 }, targetQuality: 0.75, unlockRule: q.intermediate, regressRule: { failedExposures: 3, minQuality: 0.75, painBlocks: true }, volumeRule: 'TECHNIQUE_NO_VOLUME', prerequisites: ['wall-walk'], progressions: ['controlled-kick-up'], regressions: ['wall-walk'], replacementCandidates: [] },
  { id: 'controlled-kick-up', familyId: 'handstand', name: 'Controlled Kick-up', nameAr: 'رفعة متحكم بها', stage: 5, difficulty: 'intermediate', apparatus: ['wall'], staticOrDynamic: 'dynamic', bentOrStraightArm: 'straight', role: 'technique', riskLevel: 'medium', targetDose: { sets: 5, repsMin: 3, repsMax: 5 }, targetQuality: 0.75, unlockRule: q.intermediate, regressRule: { failedExposures: 3, minQuality: 0.75, painBlocks: true }, volumeRule: 'TECHNIQUE_NO_VOLUME', prerequisites: ['handstand-wall'], progressions: ['freestanding-handstand'], regressions: ['handstand-wall'], replacementCandidates: [] },
  { id: 'freestanding-handstand', familyId: 'handstand', name: 'Freestanding Handstand', nameAr: 'وقوف حر على اليدين', stage: 6, difficulty: 'advanced', apparatus: ['floor', 'wall'], staticOrDynamic: 'static', bentOrStraightArm: 'straight', role: 'skill', riskLevel: 'high', targetDose: { sets: 6, holdSecondsMin: 10, holdSecondsMax: 20 }, targetQuality: 0.8, unlockRule: q.advanced, regressRule: { failedExposures: 3, minQuality: 0.8, painBlocks: true }, volumeRule: 'TECHNIQUE_NO_VOLUME', prerequisites: ['controlled-kick-up'], progressions: ['handstand-walking'], regressions: ['controlled-kick-up'], replacementCandidates: [] },
  { id: 'wall-hspu', familyId: 'handstand', name: 'Wall Handstand Push-up', nameAr: 'دفع على اليدين بالجدار', stage: 5, difficulty: 'advanced', apparatus: ['wall'], staticOrDynamic: 'dynamic', bentOrStraightArm: 'bent', role: 'strength', riskLevel: 'high', targetDose: { sets: 3, repsMin: 3, repsMax: 5 }, targetQuality: 0.75, unlockRule: q.advanced, regressRule: { failedExposures: 3, minQuality: 0.75, painBlocks: true }, volumeRule: 'DYNAMIC_FULL_SET', prerequisites: ['handstand-wall'], progressions: ['deficit-wall-hspu'], regressions: ['handstand-wall'], replacementCandidates: ['overhead-press'] },
  { id: 'deficit-wall-hspu', familyId: 'handstand', name: 'Deficit Wall HSPU', nameAr: 'دفع عمق بالجدار', stage: 6, difficulty: 'advanced', apparatus: ['wall', 'parallettes'], staticOrDynamic: 'dynamic', bentOrStraightArm: 'bent', role: 'strength', riskLevel: 'high', targetDose: { sets: 3, repsMin: 3, repsMax: 5 }, targetQuality: 0.8, unlockRule: q.advanced, regressRule: { failedExposures: 3, minQuality: 0.8, painBlocks: true }, volumeRule: 'DYNAMIC_FULL_SET', prerequisites: ['wall-hspu'], progressions: ['freestanding-hspu'], regressions: ['wall-hspu'], replacementCandidates: ['overhead-press'] },
  { id: 'freestanding-hspu', familyId: 'handstand', name: 'Freestanding HSPU', nameAr: 'دفع حر على اليدين', stage: 7, difficulty: 'expert', apparatus: ['floor', 'parallettes'], staticOrDynamic: 'dynamic', bentOrStraightArm: 'bent', role: 'strength', riskLevel: 'expert', targetDose: { sets: 4, repsMin: 2, repsMax: 4 }, targetQuality: 0.85, unlockRule: q.expert, regressRule: { failedExposures: 3, minQuality: 0.85, painBlocks: true }, volumeRule: 'DYNAMIC_FULL_SET', prerequisites: ['deficit-wall-hspu', 'freestanding-handstand'], progressions: ['weighted-hspu'], regressions: ['deficit-wall-hspu'], replacementCandidates: ['overhead-press'] },
  { id: 'weighted-hspu', familyId: 'handstand', name: 'Weighted HSPU', nameAr: 'دفع على اليدين مع وزن', stage: 8, difficulty: 'expert', apparatus: ['wall', 'parallettes', 'weight-vest', 'dip-belt'], staticOrDynamic: 'dynamic', bentOrStraightArm: 'bent', role: 'strength', riskLevel: 'expert', targetDose: { sets: 4, repsMin: 2, repsMax: 4 }, targetQuality: 0.85, unlockRule: q.expert, regressRule: { failedExposures: 3, minQuality: 0.85, painBlocks: true }, volumeRule: 'WEIGHTED_DYNAMIC_FULL_SET', prerequisites: ['freestanding-hspu'], progressions: [], regressions: ['freestanding-hspu'], replacementCandidates: ['overhead-press'] },
  { id: 'handstand-walking', familyId: 'handstand', name: 'Handstand Walking', nameAr: 'مشي على اليدين', stage: 7, difficulty: 'expert', apparatus: ['floor'], staticOrDynamic: 'dynamic', bentOrStraightArm: 'straight', role: 'skill', riskLevel: 'high', targetDose: { sets: 4, repsMin: 5, repsMax: 10 }, targetQuality: 0.8, unlockRule: q.advanced, regressRule: { failedExposures: 3, minQuality: 0.8, painBlocks: true }, volumeRule: 'TECHNIQUE_NO_VOLUME', prerequisites: ['freestanding-handstand'], progressions: [], regressions: ['freestanding-handstand'], replacementCandidates: [] },

  // Ring push-up tree
  { id: 'ring-plank', familyId: 'ring-push-up', name: 'Ring Plank', nameAr: 'لوح بالحلقات', stage: 1, difficulty: 'beginner', apparatus: ['rings'], staticOrDynamic: 'static', bentOrStraightArm: 'straight', role: 'technique', riskLevel: 'low', targetDose: { sets: 3, holdSecondsMin: 15, holdSecondsMax: 30 }, targetQuality: 0.7, unlockRule: q.beginner, regressRule: { failedExposures: 3, minQuality: 0.7, painBlocks: true }, volumeRule: 'TECHNIQUE_NO_VOLUME', prerequisites: [], progressions: ['ring-support'], regressions: [], replacementCandidates: [] },
  { id: 'ring-support', familyId: 'ring-push-up', name: 'Ring Support', nameAr: 'دعم الحلقات', stage: 2, difficulty: 'beginner', apparatus: ['rings'], staticOrDynamic: 'static', bentOrStraightArm: 'straight', role: 'technique', riskLevel: 'low', targetDose: { sets: 3, holdSecondsMin: 15, holdSecondsMax: 30 }, targetQuality: 0.7, unlockRule: q.beginner, regressRule: { failedExposures: 3, minQuality: 0.7, painBlocks: true }, volumeRule: 'TECHNIQUE_NO_VOLUME', prerequisites: ['ring-plank'], progressions: ['assisted-ring-push-up'], regressions: ['ring-plank'], replacementCandidates: [] },
  { id: 'assisted-ring-push-up', familyId: 'ring-push-up', name: 'Assisted Ring Push-up', nameAr: 'ضغط بالحلقات مساعد', stage: 3, difficulty: 'beginner', apparatus: ['rings', 'bands'], staticOrDynamic: 'dynamic', bentOrStraightArm: 'bent', role: 'skill', riskLevel: 'medium', targetDose: { sets: 3, repsMin: 5, repsMax: 8 }, targetQuality: 0.75, unlockRule: q.beginner, regressRule: { failedExposures: 3, minQuality: 0.75, painBlocks: true }, volumeRule: 'DYNAMIC_FULL_SET', prerequisites: ['ring-support'], progressions: ['ring-push-up'], regressions: ['ring-support'], replacementCandidates: ['bench-press'] },
  { id: 'ring-push-up', familyId: 'ring-push-up', name: 'Ring Push-up', nameAr: 'ضغط بالحلقات', stage: 4, difficulty: 'intermediate', apparatus: ['rings'], staticOrDynamic: 'dynamic', bentOrStraightArm: 'bent', role: 'skill', riskLevel: 'medium', targetDose: { sets: 3, repsMin: 6, repsMax: 10 }, targetQuality: 0.75, unlockRule: q.intermediate, regressRule: { failedExposures: 3, minQuality: 0.75, painBlocks: true }, volumeRule: 'DYNAMIC_FULL_SET', prerequisites: ['assisted-ring-push-up'], progressions: ['deep-ring-push-up'], regressions: ['assisted-ring-push-up'], replacementCandidates: ['bench-press'] },
  { id: 'deep-ring-push-up', familyId: 'ring-push-up', name: 'Deep Ring Push-up', nameAr: 'ضغط عمق بالحلقات', stage: 5, difficulty: 'advanced', apparatus: ['rings'], staticOrDynamic: 'dynamic', bentOrStraightArm: 'bent', role: 'strength', riskLevel: 'medium', targetDose: { sets: 3, repsMin: 5, repsMax: 8 }, targetQuality: 0.75, unlockRule: q.intermediate, regressRule: { failedExposures: 3, minQuality: 0.75, painBlocks: true }, volumeRule: 'DYNAMIC_FULL_SET', prerequisites: ['ring-push-up'], progressions: ['weighted-ring-push-up'], regressions: ['ring-push-up'], replacementCandidates: ['bench-press'] },
  { id: 'weighted-ring-push-up', familyId: 'ring-push-up', name: 'Weighted Ring Push-up', nameAr: 'ضغط بالحلقات مع وزن', stage: 6, difficulty: 'advanced', apparatus: ['rings', 'weight-vest', 'dip-belt'], staticOrDynamic: 'dynamic', bentOrStraightArm: 'bent', role: 'strength', riskLevel: 'medium', targetDose: { sets: 3, repsMin: 5, repsMax: 8 }, targetQuality: 0.75, unlockRule: q.intermediate, regressRule: { failedExposures: 3, minQuality: 0.75, painBlocks: true }, volumeRule: 'WEIGHTED_DYNAMIC_FULL_SET', prerequisites: ['deep-ring-push-up'], progressions: ['ring-dip'], regressions: ['deep-ring-push-up'], replacementCandidates: ['bench-press'] },
  { id: 'ring-dip', familyId: 'ring-push-up', name: 'Ring Dip', nameAr: 'غطس بالحلقات', stage: 7, difficulty: 'advanced', apparatus: ['rings'], staticOrDynamic: 'dynamic', bentOrStraightArm: 'bent', role: 'strength', riskLevel: 'high', targetDose: { sets: 3, repsMin: 4, repsMax: 8 }, targetQuality: 0.8, unlockRule: q.advanced, regressRule: { failedExposures: 3, minQuality: 0.8, painBlocks: true }, volumeRule: 'DYNAMIC_FULL_SET', prerequisites: ['weighted-ring-push-up'], progressions: ['weighted-ring-dip'], regressions: ['weighted-ring-push-up'], replacementCandidates: ['bench-press'] },
  { id: 'weighted-ring-dip', familyId: 'ring-push-up', name: 'Weighted Ring Dip', nameAr: 'غطس بالحلقات مع وزن', stage: 8, difficulty: 'expert', apparatus: ['rings', 'dip-belt'], staticOrDynamic: 'dynamic', bentOrStraightArm: 'bent', role: 'strength', riskLevel: 'expert', targetDose: { sets: 3, repsMin: 3, repsMax: 6 }, targetQuality: 0.85, unlockRule: q.expert, regressRule: { failedExposures: 3, minQuality: 0.85, painBlocks: true }, volumeRule: 'WEIGHTED_DYNAMIC_FULL_SET', prerequisites: ['ring-dip'], progressions: [], regressions: ['ring-dip'], replacementCandidates: ['bench-press'] },

  // Pistol tree
  { id: 'ankle-mobility', familyId: 'pistol', name: 'Ankle Mobility', nameAr: 'حرية الكاحل', stage: 1, difficulty: 'fundamental', apparatus: ['exercise-mat'], staticOrDynamic: 'dynamic', bentOrStraightArm: 'bent', role: 'technique', riskLevel: 'low', targetDose: { sets: 2, repsMin: 8, repsMax: 10 }, targetQuality: 0.7, unlockRule: q.beginner, regressRule: { failedExposures: 3, minQuality: 0.7, painBlocks: true }, volumeRule: 'TECHNIQUE_NO_VOLUME', prerequisites: [], progressions: ['deep-bilateral-squat'], regressions: [], replacementCandidates: [] },
  { id: 'deep-bilateral-squat', familyId: 'pistol', name: 'Deep Bilateral Squat', nameAr: 'قرفصاء ثنائية عميقة', stage: 2, difficulty: 'beginner', apparatus: ['exercise-mat'], staticOrDynamic: 'dynamic', bentOrStraightArm: 'bent', role: 'technique', riskLevel: 'low', targetDose: { sets: 3, repsMin: 5, repsMax: 8 }, targetQuality: 0.7, unlockRule: q.beginner, regressRule: { failedExposures: 3, minQuality: 0.7, painBlocks: true }, volumeRule: 'TECHNIQUE_NO_VOLUME', prerequisites: ['ankle-mobility'], progressions: ['step-down'], regressions: ['ankle-mobility'], replacementCandidates: [] },
  { id: 'step-down', familyId: 'pistol', name: 'Controlled Step-down', nameAr: 'نزول متحكم من صندوق', stage: 3, difficulty: 'beginner', apparatus: ['box'], staticOrDynamic: 'dynamic', bentOrStraightArm: 'bent', role: 'skill', riskLevel: 'low', targetDose: { sets: 3, repsMin: 4, repsMax: 6 }, targetQuality: 0.75, unlockRule: q.beginner, regressRule: { failedExposures: 3, minQuality: 0.75, painBlocks: true }, volumeRule: 'DYNAMIC_FULL_SET', prerequisites: ['deep-bilateral-squat'], progressions: ['box-pistol'], regressions: ['deep-bilateral-squat'], replacementCandidates: [] },
  { id: 'box-pistol', familyId: 'pistol', name: 'Box Pistol', nameAr: 'قرفصاء برجل واحدة على صندوق', stage: 4, difficulty: 'intermediate', apparatus: ['box'], staticOrDynamic: 'dynamic', bentOrStraightArm: 'bent', role: 'skill', riskLevel: 'medium', targetDose: { sets: 3, repsMin: 4, repsMax: 6 }, targetQuality: 0.75, unlockRule: q.intermediate, regressRule: { failedExposures: 3, minQuality: 0.75, painBlocks: true }, volumeRule: 'DYNAMIC_FULL_SET', prerequisites: ['step-down'], progressions: ['assisted-pistol'], regressions: ['step-down'], replacementCandidates: ['back-squat'] },
  { id: 'assisted-pistol', familyId: 'pistol', name: 'Assisted Pistol', nameAr: 'قرفصاء برجل واحدة مساعدة', stage: 5, difficulty: 'intermediate', apparatus: ['box', 'bands'], staticOrDynamic: 'dynamic', bentOrStraightArm: 'bent', role: 'skill', riskLevel: 'medium', targetDose: { sets: 3, repsMin: 3, repsMax: 5 }, targetQuality: 0.75, unlockRule: q.intermediate, regressRule: { failedExposures: 3, minQuality: 0.75, painBlocks: true }, volumeRule: 'DYNAMIC_FULL_SET', prerequisites: ['box-pistol'], progressions: ['counterweight-pistol'], regressions: ['box-pistol'], replacementCandidates: ['back-squat'] },
  { id: 'counterweight-pistol', familyId: 'pistol', name: 'Counterweight Pistol', nameAr: 'قرفصاء برجل واحدة بثقل معاكس', stage: 6, difficulty: 'intermediate', apparatus: ['box', 'dumbbells'], staticOrDynamic: 'dynamic', bentOrStraightArm: 'bent', role: 'skill', riskLevel: 'medium', targetDose: { sets: 3, repsMin: 3, repsMax: 5 }, targetQuality: 0.75, unlockRule: q.intermediate, regressRule: { failedExposures: 3, minQuality: 0.75, painBlocks: true }, volumeRule: 'DYNAMIC_FULL_SET', prerequisites: ['assisted-pistol'], progressions: ['full-pistol'], regressions: ['assisted-pistol'], replacementCandidates: ['back-squat'] },
  { id: 'full-pistol', familyId: 'pistol', name: 'Full Pistol', nameAr: 'قرفصاء برجل واحدة كاملة', stage: 7, difficulty: 'intermediate', apparatus: ['box'], staticOrDynamic: 'dynamic', bentOrStraightArm: 'bent', role: 'strength', riskLevel: 'medium', targetDose: { sets: 3, repsMin: 3, repsMax: 5 }, targetQuality: 0.75, unlockRule: q.intermediate, regressRule: { failedExposures: 3, minQuality: 0.75, painBlocks: true }, volumeRule: 'DYNAMIC_FULL_SET', prerequisites: ['counterweight-pistol'], progressions: ['paused-pistol'], regressions: ['counterweight-pistol'], replacementCandidates: ['back-squat'] },
  { id: 'paused-pistol', familyId: 'pistol', name: 'Paused Pistol', nameAr: 'قرفصاء برجل واحدة متوقفة', stage: 8, difficulty: 'advanced', apparatus: ['box'], staticOrDynamic: 'dynamic', bentOrStraightArm: 'bent', role: 'strength', riskLevel: 'medium', targetDose: { sets: 3, repsMin: 3, repsMax: 5 }, targetQuality: 0.8, unlockRule: q.advanced, regressRule: { failedExposures: 3, minQuality: 0.8, painBlocks: true }, volumeRule: 'DYNAMIC_FULL_SET', prerequisites: ['full-pistol'], progressions: ['deficit-pistol'], regressions: ['full-pistol'], replacementCandidates: ['back-squat'] },
  { id: 'deficit-pistol', familyId: 'pistol', name: 'Deficit Pistol', nameAr: 'قرفصاء برجل واحدة بعجز', stage: 9, difficulty: 'advanced', apparatus: ['box'], staticOrDynamic: 'dynamic', bentOrStraightArm: 'bent', role: 'strength', riskLevel: 'medium', targetDose: { sets: 3, repsMin: 3, repsMax: 5 }, targetQuality: 0.8, unlockRule: q.advanced, regressRule: { failedExposures: 3, minQuality: 0.8, painBlocks: true }, volumeRule: 'DYNAMIC_FULL_SET', prerequisites: ['paused-pistol'], progressions: ['weighted-pistol'], regressions: ['paused-pistol'], replacementCandidates: ['back-squat'] },
  { id: 'weighted-pistol', familyId: 'pistol', name: 'Weighted Pistol', nameAr: 'قرفصاء برجل واحدة مع وزن', stage: 10, difficulty: 'advanced', apparatus: ['box', 'dumbbells'], staticOrDynamic: 'dynamic', bentOrStraightArm: 'bent', role: 'strength', riskLevel: 'medium', targetDose: { sets: 3, repsMin: 3, repsMax: 5 }, targetQuality: 0.8, unlockRule: q.advanced, regressRule: { failedExposures: 3, minQuality: 0.8, painBlocks: true }, volumeRule: 'WEIGHTED_DYNAMIC_FULL_SET', prerequisites: ['deficit-pistol'], progressions: ['heavy-weighted-pistol'], regressions: ['deficit-pistol'], replacementCandidates: ['back-squat'] },
  { id: 'heavy-weighted-pistol', familyId: 'pistol', name: 'Heavy Weighted Pistol', nameAr: 'قرفصاء برجل واحدة ثقيلة', stage: 11, difficulty: 'expert', apparatus: ['box', 'dumbbells'], staticOrDynamic: 'dynamic', bentOrStraightArm: 'bent', role: 'strength', riskLevel: 'expert', targetDose: { sets: 3, repsMin: 2, repsMax: 4 }, targetQuality: 0.85, unlockRule: q.expert, regressRule: { failedExposures: 3, minQuality: 0.85, painBlocks: true }, volumeRule: 'WEIGHTED_DYNAMIC_FULL_SET', prerequisites: ['weighted-pistol'], progressions: [], regressions: ['weighted-pistol'], replacementCandidates: ['back-squat'] },

  // Front lever tree
  { id: 'tuck-front-lever', familyId: 'front-lever', name: 'Tuck Front Lever', nameAr: 'رافعة أمامية مطوية', stage: 1, difficulty: 'intermediate', apparatus: ['pull-up-bar'], staticOrDynamic: 'static', bentOrStraightArm: 'straight', role: 'skill', riskLevel: 'high', targetDose: { sets: 4, holdSecondsMin: 6, holdSecondsMax: 10 }, targetQuality: 0.7, unlockRule: q.intermediate, regressRule: { failedExposures: 3, minQuality: 0.7, painBlocks: true }, volumeRule: 'STATIC_EXPOSURE', prerequisites: ['active-hang'], progressions: ['advanced-tuck-front-lever'], regressions: ['active-hang'], replacementCandidates: ['chest-supported-row'] },
  { id: 'advanced-tuck-front-lever', familyId: 'front-lever', name: 'Advanced Tuck Front Lever', nameAr: 'رافعة أمامية مطوية متقدمة', stage: 2, difficulty: 'intermediate', apparatus: ['pull-up-bar'], staticOrDynamic: 'static', bentOrStraightArm: 'straight', role: 'skill', riskLevel: 'high', targetDose: { sets: 4, holdSecondsMin: 6, holdSecondsMax: 10 }, targetQuality: 0.75, unlockRule: q.intermediate, regressRule: { failedExposures: 3, minQuality: 0.75, painBlocks: true }, volumeRule: 'STATIC_EXPOSURE', prerequisites: ['tuck-front-lever'], progressions: ['one-leg-front-lever'], regressions: ['tuck-front-lever'], replacementCandidates: ['chest-supported-row'] },
  { id: 'one-leg-front-lever', familyId: 'front-lever', name: 'One-leg Front Lever', nameAr: 'رافعة أمامية برجل واحدة', stage: 3, difficulty: 'advanced', apparatus: ['pull-up-bar'], staticOrDynamic: 'static', bentOrStraightArm: 'straight', role: 'skill', riskLevel: 'high', targetDose: { sets: 4, holdSecondsMin: 6, holdSecondsMax: 10 }, targetQuality: 0.75, unlockRule: q.advanced, regressRule: { failedExposures: 3, minQuality: 0.75, painBlocks: true }, volumeRule: 'STATIC_EXPOSURE', prerequisites: ['advanced-tuck-front-lever'], progressions: ['straddle-front-lever'], regressions: ['advanced-tuck-front-lever'], replacementCandidates: ['chest-supported-row'] },
  { id: 'straddle-front-lever', familyId: 'front-lever', name: 'Straddle Front Lever', nameAr: 'رافعة أمامية مفتوحة', stage: 4, difficulty: 'advanced', apparatus: ['pull-up-bar'], staticOrDynamic: 'static', bentOrStraightArm: 'straight', role: 'skill', riskLevel: 'high', targetDose: { sets: 4, holdSecondsMin: 6, holdSecondsMax: 10 }, targetQuality: 0.8, unlockRule: q.advanced, regressRule: { failedExposures: 3, minQuality: 0.8, painBlocks: true }, volumeRule: 'STATIC_EXPOSURE', prerequisites: ['one-leg-front-lever'], progressions: ['full-front-lever'], regressions: ['one-leg-front-lever'], replacementCandidates: ['chest-supported-row'] },
  { id: 'full-front-lever', familyId: 'front-lever', name: 'Full Front Lever', nameAr: 'رافعة أمامية كاملة', stage: 5, difficulty: 'advanced', apparatus: ['pull-up-bar'], staticOrDynamic: 'static', bentOrStraightArm: 'straight', role: 'skill', riskLevel: 'high', targetDose: { sets: 4, holdSecondsMin: 6, holdSecondsMax: 10 }, targetQuality: 0.8, unlockRule: q.advanced, regressRule: { failedExposures: 3, minQuality: 0.8, painBlocks: true }, volumeRule: 'STATIC_EXPOSURE', prerequisites: ['straddle-front-lever'], progressions: ['front-lever-row'], regressions: ['straddle-front-lever'], replacementCandidates: ['chest-supported-row'] },
  { id: 'front-lever-row', familyId: 'front-lever', name: 'Front Lever Row', nameAr: 'سحب الرافعة الأمامية', stage: 6, difficulty: 'expert', apparatus: ['pull-up-bar'], staticOrDynamic: 'dynamic', bentOrStraightArm: 'bent', role: 'strength', riskLevel: 'expert', targetDose: { sets: 3, repsMin: 3, repsMax: 5 }, targetQuality: 0.85, unlockRule: q.expert, regressRule: { failedExposures: 3, minQuality: 0.85, painBlocks: true }, volumeRule: 'DYNAMIC_FULL_SET', prerequisites: ['full-front-lever'], progressions: ['weighted-front-lever'], regressions: ['full-front-lever'], replacementCandidates: ['chest-supported-row'] },
  { id: 'weighted-front-lever', familyId: 'front-lever', name: 'Weighted Front Lever', nameAr: 'رافعة أمامية مع وزن', stage: 7, difficulty: 'expert', apparatus: ['pull-up-bar', 'dip-belt'], staticOrDynamic: 'static', bentOrStraightArm: 'straight', role: 'strength', riskLevel: 'expert', targetDose: { sets: 4, holdSecondsMin: 6, holdSecondsMax: 10 }, targetQuality: 0.85, unlockRule: q.expert, regressRule: { failedExposures: 3, minQuality: 0.85, painBlocks: true }, volumeRule: 'STATIC_EXPOSURE', prerequisites: ['front-lever-row'], progressions: [], regressions: ['front-lever-row'], replacementCandidates: ['chest-supported-row'] },

  // Back lever tree
  { id: 'skin-the-cat', familyId: 'back-lever', name: 'Skin the Cat', nameAr: 'تقشير القط', stage: 1, difficulty: 'beginner', apparatus: ['pull-up-bar', 'rings'], staticOrDynamic: 'dynamic', bentOrStraightArm: 'straight', role: 'technique', riskLevel: 'medium', targetDose: { sets: 3, repsMin: 3, repsMax: 5 }, targetQuality: 0.7, unlockRule: q.beginner, regressRule: { failedExposures: 3, minQuality: 0.7, painBlocks: true }, volumeRule: 'TECHNIQUE_NO_VOLUME', prerequisites: ['active-hang'], progressions: ['german-hang'], regressions: [], replacementCandidates: [] },
  { id: 'german-hang', familyId: 'back-lever', name: 'German Hang', nameAr: 'تعليق ألماني', stage: 2, difficulty: 'intermediate', apparatus: ['pull-up-bar', 'rings'], staticOrDynamic: 'static', bentOrStraightArm: 'straight', role: 'technique', riskLevel: 'medium', targetDose: { sets: 3, holdSecondsMin: 10, holdSecondsMax: 20 }, targetQuality: 0.75, unlockRule: q.intermediate, regressRule: { failedExposures: 3, minQuality: 0.75, painBlocks: true }, volumeRule: 'TECHNIQUE_NO_VOLUME', prerequisites: ['skin-the-cat'], progressions: ['tuck-back-lever'], regressions: ['skin-the-cat'], replacementCandidates: [] },
  { id: 'tuck-back-lever', familyId: 'back-lever', name: 'Tuck Back Lever', nameAr: 'رافعة خلفية مطوية', stage: 3, difficulty: 'intermediate', apparatus: ['pull-up-bar', 'rings'], staticOrDynamic: 'static', bentOrStraightArm: 'straight', role: 'skill', riskLevel: 'high', targetDose: { sets: 4, holdSecondsMin: 6, holdSecondsMax: 10 }, targetQuality: 0.75, unlockRule: q.intermediate, regressRule: { failedExposures: 3, minQuality: 0.75, painBlocks: true }, volumeRule: 'STATIC_EXPOSURE', prerequisites: ['german-hang'], progressions: ['advanced-tuck-back-lever'], regressions: ['german-hang'], replacementCandidates: [] },
  { id: 'advanced-tuck-back-lever', familyId: 'back-lever', name: 'Advanced Tuck Back Lever', nameAr: 'رافعة خلفية مطوية متقدمة', stage: 4, difficulty: 'advanced', apparatus: ['pull-up-bar', 'rings'], staticOrDynamic: 'static', bentOrStraightArm: 'straight', role: 'skill', riskLevel: 'high', targetDose: { sets: 4, holdSecondsMin: 6, holdSecondsMax: 10 }, targetQuality: 0.8, unlockRule: q.advanced, regressRule: { failedExposures: 3, minQuality: 0.8, painBlocks: true }, volumeRule: 'STATIC_EXPOSURE', prerequisites: ['tuck-back-lever'], progressions: ['straddle-back-lever'], regressions: ['tuck-back-lever'], replacementCandidates: [] },
  { id: 'straddle-back-lever', familyId: 'back-lever', name: 'Straddle Back Lever', nameAr: 'رافعة خلفية مفتوحة', stage: 5, difficulty: 'advanced', apparatus: ['pull-up-bar', 'rings'], staticOrDynamic: 'static', bentOrStraightArm: 'straight', role: 'skill', riskLevel: 'high', targetDose: { sets: 4, holdSecondsMin: 6, holdSecondsMax: 10 }, targetQuality: 0.8, unlockRule: q.advanced, regressRule: { failedExposures: 3, minQuality: 0.8, painBlocks: true }, volumeRule: 'STATIC_EXPOSURE', prerequisites: ['advanced-tuck-back-lever'], progressions: ['full-back-lever'], regressions: ['advanced-tuck-back-lever'], replacementCandidates: [] },
  { id: 'full-back-lever', familyId: 'back-lever', name: 'Full Back Lever', nameAr: 'رافعة خلفية كاملة', stage: 6, difficulty: 'expert', apparatus: ['pull-up-bar', 'rings'], staticOrDynamic: 'static', bentOrStraightArm: 'straight', role: 'skill', riskLevel: 'expert', targetDose: { sets: 4, holdSecondsMin: 6, holdSecondsMax: 10 }, targetQuality: 0.85, unlockRule: q.expert, regressRule: { failedExposures: 3, minQuality: 0.85, painBlocks: true }, volumeRule: 'STATIC_EXPOSURE', prerequisites: ['straddle-back-lever'], progressions: ['weighted-back-lever'], regressions: ['straddle-back-lever'], replacementCandidates: [] },
  { id: 'weighted-back-lever', familyId: 'back-lever', name: 'Weighted Back Lever', nameAr: 'رافعة خلفية مع وزن', stage: 7, difficulty: 'expert', apparatus: ['pull-up-bar', 'rings', 'dip-belt'], staticOrDynamic: 'static', bentOrStraightArm: 'straight', role: 'strength', riskLevel: 'expert', targetDose: { sets: 4, holdSecondsMin: 6, holdSecondsMax: 10 }, targetQuality: 0.85, unlockRule: q.expert, regressRule: { failedExposures: 3, minQuality: 0.85, painBlocks: true }, volumeRule: 'STATIC_EXPOSURE', prerequisites: ['full-back-lever'], progressions: [], regressions: ['full-back-lever'], replacementCandidates: [] },

  // Planche tree
  { id: 'planche-wrist-prep', familyId: 'planche', name: 'Planche Wrist Prep', nameAr: 'إعداد معصم البلانش', stage: 1, difficulty: 'fundamental', apparatus: ['floor'], staticOrDynamic: 'static', bentOrStraightArm: 'straight', role: 'technique', riskLevel: 'low', targetDose: { sets: 1, holdSecondsMin: 180, holdSecondsMax: 300 }, targetQuality: 0.7, unlockRule: q.beginner, regressRule: { failedExposures: 3, minQuality: 0.7, painBlocks: true }, volumeRule: 'TECHNIQUE_NO_VOLUME', prerequisites: [], progressions: ['planche-lean'], regressions: [], replacementCandidates: [] },
  { id: 'planche-lean', familyId: 'planche', name: 'Planche Lean', nameAr: 'ميل البلانش', stage: 2, difficulty: 'beginner', apparatus: ['floor', 'parallettes'], staticOrDynamic: 'static', bentOrStraightArm: 'straight', role: 'technique', riskLevel: 'low', targetDose: { sets: 4, holdSecondsMin: 10, holdSecondsMax: 20 }, targetQuality: 0.7, unlockRule: q.beginner, regressRule: { failedExposures: 3, minQuality: 0.7, painBlocks: true }, volumeRule: 'TECHNIQUE_NO_VOLUME', prerequisites: ['planche-wrist-prep'], progressions: ['tuck-planche'], regressions: ['planche-wrist-prep'], replacementCandidates: [] },
  { id: 'frog-stand', familyId: 'planche', name: 'Frog Stand', nameAr: 'وقوف الضفدع', stage: 3, difficulty: 'beginner', apparatus: ['floor', 'parallettes'], staticOrDynamic: 'static', bentOrStraightArm: 'bent', role: 'technique', riskLevel: 'low', targetDose: { sets: 3, holdSecondsMin: 15, holdSecondsMax: 30 }, targetQuality: 0.7, unlockRule: q.beginner, regressRule: { failedExposures: 3, minQuality: 0.7, painBlocks: true }, volumeRule: 'TECHNIQUE_NO_VOLUME', prerequisites: ['planche-lean'], progressions: ['tuck-planche'], regressions: ['planche-lean'], replacementCandidates: [] },
  { id: 'tuck-planche', familyId: 'planche', name: 'Tuck Planche', nameAr: 'بلانش مطوي', stage: 4, difficulty: 'intermediate', apparatus: ['floor', 'parallettes'], staticOrDynamic: 'static', bentOrStraightArm: 'straight', role: 'skill', riskLevel: 'high', targetDose: { sets: 4, holdSecondsMin: 6, holdSecondsMax: 10 }, targetQuality: 0.75, unlockRule: q.intermediate, regressRule: { failedExposures: 3, minQuality: 0.75, painBlocks: true }, volumeRule: 'STATIC_EXPOSURE', prerequisites: ['planche-lean', 'frog-stand'], progressions: ['advanced-tuck-planche'], regressions: ['planche-lean'], replacementCandidates: ['bench-press'] },
  { id: 'advanced-tuck-planche', familyId: 'planche', name: 'Advanced Tuck Planche', nameAr: 'بلانش مطوي متقدم', stage: 5, difficulty: 'advanced', apparatus: ['floor', 'parallettes'], staticOrDynamic: 'static', bentOrStraightArm: 'straight', role: 'skill', riskLevel: 'high', targetDose: { sets: 4, holdSecondsMin: 6, holdSecondsMax: 10 }, targetQuality: 0.8, unlockRule: q.advanced, regressRule: { failedExposures: 3, minQuality: 0.8, painBlocks: true }, volumeRule: 'STATIC_EXPOSURE', prerequisites: ['tuck-planche'], progressions: ['straddle-planche'], regressions: ['tuck-planche'], replacementCandidates: ['bench-press'] },
  { id: 'straddle-planche', familyId: 'planche', name: 'Straddle Planche', nameAr: 'بلانش مفتوح', stage: 6, difficulty: 'advanced', apparatus: ['floor', 'parallettes'], staticOrDynamic: 'static', bentOrStraightArm: 'straight', role: 'skill', riskLevel: 'high', targetDose: { sets: 4, holdSecondsMin: 6, holdSecondsMax: 10 }, targetQuality: 0.8, unlockRule: q.advanced, regressRule: { failedExposures: 3, minQuality: 0.8, painBlocks: true }, volumeRule: 'STATIC_EXPOSURE', prerequisites: ['advanced-tuck-planche'], progressions: ['full-planche'], regressions: ['advanced-tuck-planche'], replacementCandidates: ['bench-press'] },
  { id: 'full-planche', familyId: 'planche', name: 'Full Planche', nameAr: 'بلانش كامل', stage: 7, difficulty: 'expert', apparatus: ['floor', 'parallettes'], staticOrDynamic: 'static', bentOrStraightArm: 'straight', role: 'skill', riskLevel: 'expert', targetDose: { sets: 4, holdSecondsMin: 6, holdSecondsMax: 10 }, targetQuality: 0.85, unlockRule: q.expert, regressRule: { failedExposures: 3, minQuality: 0.85, painBlocks: true }, volumeRule: 'STATIC_EXPOSURE', prerequisites: ['straddle-planche'], progressions: ['planche-push-up'], regressions: ['straddle-planche'], replacementCandidates: ['bench-press'] },
  { id: 'planche-push-up', familyId: 'planche', name: 'Planche Push-up', nameAr: 'ضغطة بلانش', stage: 8, difficulty: 'expert', apparatus: ['floor', 'parallettes'], staticOrDynamic: 'dynamic', bentOrStraightArm: 'straight', role: 'strength', riskLevel: 'expert', targetDose: { sets: 4, repsMin: 2, repsMax: 4 }, targetQuality: 0.85, unlockRule: q.expert, regressRule: { failedExposures: 3, minQuality: 0.85, painBlocks: true }, volumeRule: 'DYNAMIC_FULL_SET', prerequisites: ['full-planche'], progressions: ['planche-press'], regressions: ['full-planche'], replacementCandidates: ['bench-press'] },
  { id: 'planche-press', familyId: 'planche', name: 'Planche Press to Handstand', nameAr: 'ضغطة بلانش إلى وقوف', stage: 9, difficulty: 'expert', apparatus: ['floor', 'parallettes'], staticOrDynamic: 'dynamic', bentOrStraightArm: 'straight', role: 'strength', riskLevel: 'expert', targetDose: { sets: 4, repsMin: 1, repsMax: 3 }, targetQuality: 0.85, unlockRule: q.expert, regressRule: { failedExposures: 3, minQuality: 0.85, painBlocks: true }, volumeRule: 'DYNAMIC_FULL_SET', prerequisites: ['planche-push-up', 'freestanding-handstand'], progressions: [], regressions: ['planche-push-up'], replacementCandidates: ['bench-press'] },

  // L-sit tree
  { id: 'support-hold', familyId: 'l-sit', name: 'Support Hold', nameAr: 'تمسك الدعم', stage: 1, difficulty: 'fundamental', apparatus: ['parallettes', 'floor'], staticOrDynamic: 'static', bentOrStraightArm: 'straight', role: 'technique', riskLevel: 'low', targetDose: { sets: 3, holdSecondsMin: 20, holdSecondsMax: 30 }, targetQuality: 0.7, unlockRule: q.beginner, regressRule: { failedExposures: 3, minQuality: 0.7, painBlocks: true }, volumeRule: 'TECHNIQUE_NO_VOLUME', prerequisites: [], progressions: ['tuck-sit'], regressions: [], replacementCandidates: [] },
  { id: 'tuck-sit', familyId: 'l-sit', name: 'Tuck Sit', nameAr: 'جلوس مطوي', stage: 2, difficulty: 'beginner', apparatus: ['parallettes', 'floor'], staticOrDynamic: 'static', bentOrStraightArm: 'straight', role: 'technique', riskLevel: 'low', targetDose: { sets: 3, holdSecondsMin: 10, holdSecondsMax: 20 }, targetQuality: 0.7, unlockRule: q.beginner, regressRule: { failedExposures: 3, minQuality: 0.7, painBlocks: true }, volumeRule: 'TECHNIQUE_NO_VOLUME', prerequisites: ['support-hold'], progressions: ['one-leg-l-sit'], regressions: ['support-hold'], replacementCandidates: [] },
  { id: 'one-leg-l-sit', familyId: 'l-sit', name: 'One-leg L-sit', nameAr: 'جلوس L برجل واحدة', stage: 3, difficulty: 'intermediate', apparatus: ['parallettes', 'floor'], staticOrDynamic: 'static', bentOrStraightArm: 'straight', role: 'skill', riskLevel: 'low', targetDose: { sets: 3, holdSecondsMin: 10, holdSecondsMax: 20 }, targetQuality: 0.75, unlockRule: q.intermediate, regressRule: { failedExposures: 3, minQuality: 0.75, painBlocks: true }, volumeRule: 'STATIC_EXPOSURE', prerequisites: ['tuck-sit'], progressions: ['l-sit'], regressions: ['tuck-sit'], replacementCandidates: [] },
  { id: 'l-sit', familyId: 'l-sit', name: 'L-sit', nameAr: 'جلوس L', stage: 4, difficulty: 'intermediate', apparatus: ['parallettes', 'floor', 'rings'], staticOrDynamic: 'static', bentOrStraightArm: 'straight', role: 'skill', riskLevel: 'low', targetDose: { sets: 4, holdSecondsMin: 10, holdSecondsMax: 20 }, targetQuality: 0.75, unlockRule: q.intermediate, regressRule: { failedExposures: 3, minQuality: 0.75, painBlocks: true }, volumeRule: 'STATIC_EXPOSURE', prerequisites: ['one-leg-l-sit'], progressions: ['elevated-l-sit'], regressions: ['one-leg-l-sit'], replacementCandidates: [] },
  { id: 'elevated-l-sit', familyId: 'l-sit', name: 'Elevated L-sit', nameAr: 'جلوس L مرتفع', stage: 5, difficulty: 'advanced', apparatus: ['parallettes', 'box'], staticOrDynamic: 'static', bentOrStraightArm: 'straight', role: 'skill', riskLevel: 'medium', targetDose: { sets: 4, holdSecondsMin: 10, holdSecondsMax: 20 }, targetQuality: 0.8, unlockRule: q.advanced, regressRule: { failedExposures: 3, minQuality: 0.8, painBlocks: true }, volumeRule: 'STATIC_EXPOSURE', prerequisites: ['l-sit'], progressions: ['v-sit'], regressions: ['l-sit'], replacementCandidates: [] },
  { id: 'v-sit', familyId: 'l-sit', name: 'V-sit', nameAr: 'جلوس V', stage: 6, difficulty: 'expert', apparatus: ['parallettes', 'floor'], staticOrDynamic: 'static', bentOrStraightArm: 'straight', role: 'skill', riskLevel: 'high', targetDose: { sets: 4, holdSecondsMin: 6, holdSecondsMax: 10 }, targetQuality: 0.85, unlockRule: q.expert, regressRule: { failedExposures: 3, minQuality: 0.85, painBlocks: true }, volumeRule: 'STATIC_EXPOSURE', prerequisites: ['elevated-l-sit'], progressions: ['press-handstand-prep'], regressions: ['elevated-l-sit'], replacementCandidates: [] },
  { id: 'press-handstand-prep', familyId: 'l-sit', name: 'Press Handstand Prep', nameAr: 'تحضير الوقوف بالضغط', stage: 7, difficulty: 'expert', apparatus: ['parallettes', 'floor'], staticOrDynamic: 'dynamic', bentOrStraightArm: 'straight', role: 'skill', riskLevel: 'expert', targetDose: { sets: 4, repsMin: 2, repsMax: 4 }, targetQuality: 0.85, unlockRule: q.expert, regressRule: { failedExposures: 3, minQuality: 0.85, painBlocks: true }, volumeRule: 'DYNAMIC_FULL_SET', prerequisites: ['v-sit', 'freestanding-handstand'], progressions: [], regressions: ['v-sit'], replacementCandidates: [] },

  // Expert ring branches
  { id: 'iron-cross', familyId: 'expert-rings', name: 'Iron Cross', nameAr: 'صليب الحديد', stage: 1, difficulty: 'expert', apparatus: ['rings'], staticOrDynamic: 'static', bentOrStraightArm: 'straight', role: 'skill', riskLevel: 'expert', targetDose: { sets: 4, holdSecondsMin: 3, holdSecondsMax: 6 }, targetQuality: 0.85, unlockRule: q.expert, regressRule: { failedExposures: 3, minQuality: 0.85, painBlocks: true }, volumeRule: 'EXPERT_STATIC_LOCKED', prerequisites: ['full-planche', 'full-front-lever'], progressions: [], regressions: ['straddle-planche'], replacementCandidates: [] },
  { id: 'maltese', familyId: 'expert-rings', name: 'Maltese', nameAr: 'مالتيز', stage: 1, difficulty: 'expert', apparatus: ['rings'], staticOrDynamic: 'static', bentOrStraightArm: 'straight', role: 'skill', riskLevel: 'expert', targetDose: { sets: 4, holdSecondsMin: 3, holdSecondsMax: 6 }, targetQuality: 0.85, unlockRule: q.expert, regressRule: { failedExposures: 3, minQuality: 0.85, painBlocks: true }, volumeRule: 'EXPERT_STATIC_LOCKED', prerequisites: ['full-planche'], progressions: [], regressions: ['straddle-planche'], replacementCandidates: [] },
  { id: 'victorian', familyId: 'expert-rings', name: 'Victorian', nameAr: 'فيكتوريان', stage: 1, difficulty: 'expert', apparatus: ['rings'], staticOrDynamic: 'static', bentOrStraightArm: 'straight', role: 'skill', riskLevel: 'expert', targetDose: { sets: 4, holdSecondsMin: 3, holdSecondsMax: 6 }, targetQuality: 0.85, unlockRule: q.expert, regressRule: { failedExposures: 3, minQuality: 0.85, painBlocks: true }, volumeRule: 'EXPERT_STATIC_LOCKED', prerequisites: ['full-front-lever'], progressions: [], regressions: ['straddle-front-lever'], replacementCandidates: [] }
];

export function getSkillNode(id: string): SkillNode | undefined {
  return SKILL_NODES.find((n) => n.id === id);
}

export function getNodesByFamily(familyId: string): SkillNode[] {
  return SKILL_NODES.filter((n) => n.familyId === familyId).sort((a, b) => a.stage - b.stage);
}
