import type { Exercise } from '../types.js';

export const EXERCISE_CATALOG: Record<string, Exercise> = {
  // Day 1
  'back-squat': {
    id: 'back-squat',
    movementPatternId: 'KNEE_DOMINANT',
    name: 'Back Squat',
    nameAr: 'قرفصاء خلفية',
    role: 'STRENGTH_PRIMARY',
    orderClass: 'GYM_STRENGTH',
    equipmentIds: ['barbell', 'squat-rack', 'plates'],
    primaryMuscleIds: ['quadriceps'],
    secondaryMuscleIds: ['glutes'],
    requiresGym: true,
    canBeReplaced: true,
    defaultWarmupSeconds: 240,
    defaultWorkingSetSeconds: 60,
    transitionSeconds: 120
  },
  'weighted-pull-up': {
    id: 'weighted-pull-up',
    movementPatternId: 'VERTICAL_PULL',
    name: 'Weighted Pull-up',
    nameAr: 'سحب مع وزن',
    role: 'STRENGTH_AND_HYPERTROPHY',
    orderClass: 'GYM_STRENGTH',
    equipmentIds: ['pull-up-bar', 'dip-belt', 'plates'],
    primaryMuscleIds: ['lats'],
    secondaryMuscleIds: ['biceps'],
    requiresGym: false,
    canBeReplaced: true,
    defaultWarmupSeconds: 120,
    defaultWorkingSetSeconds: 50,
    transitionSeconds: 90
  },
  'bench-press': {
    id: 'bench-press',
    movementPatternId: 'HORIZONTAL_PUSH',
    name: 'Barbell Bench Press',
    nameAr: 'ضغط صدر بالبار',
    role: 'STRENGTH_AND_HYPERTROPHY',
    orderClass: 'GYM_STRENGTH',
    equipmentIds: ['barbell', 'bench', 'plates'],
    primaryMuscleIds: ['chest'],
    secondaryMuscleIds: ['triceps', 'anterior-deltoids'],
    requiresGym: true,
    canBeReplaced: true,
    defaultWarmupSeconds: 180,
    defaultWorkingSetSeconds: 60,
    transitionSeconds: 90
  },
  'seated-leg-curl': {
    id: 'seated-leg-curl',
    movementPatternId: 'KNEE_FLEXION',
    name: 'Seated Leg Curl',
    nameAr: 'ثني ركبة جالس',
    role: 'HYPERTROPHY_PRIMARY',
    orderClass: 'GYM_HYPERTROPHY',
    equipmentIds: ['leg-curl'],
    primaryMuscleIds: ['hamstrings'],
    secondaryMuscleIds: [],
    requiresGym: true,
    canBeReplaced: true,
    defaultWarmupSeconds: 60,
    defaultWorkingSetSeconds: 40,
    transitionSeconds: 45
  },
  'cable-lateral-raise': {
    id: 'cable-lateral-raise',
    movementPatternId: 'CORE_COMPRESSION',
    name: 'Cable Lateral Raise',
    nameAr: 'رفع جانبي بالكابل',
    role: 'HYPERTROPHY_PRIMARY',
    orderClass: 'ACCESSORY',
    equipmentIds: ['cable'],
    primaryMuscleIds: ['lateral-deltoids'],
    secondaryMuscleIds: [],
    requiresGym: true,
    canBeReplaced: false,
    defaultWarmupSeconds: 60,
    defaultWorkingSetSeconds: 40,
    transitionSeconds: 30
  },
  'ez-curl': {
    id: 'ez-curl',
    movementPatternId: 'GRIP',
    name: 'EZ-bar Curl',
    nameAr: 'كيرل بالبار EZ',
    role: 'HYPERTROPHY_PRIMARY',
    orderClass: 'ACCESSORY',
    equipmentIds: ['barbell', 'plates'],
    primaryMuscleIds: ['biceps'],
    secondaryMuscleIds: [],
    requiresGym: true,
    canBeReplaced: false,
    defaultWarmupSeconds: 60,
    defaultWorkingSetSeconds: 40,
    transitionSeconds: 30
  },
  'triceps-pressdown': {
    id: 'triceps-pressdown',
    movementPatternId: 'GRIP',
    name: 'Rope Triceps Pressdown',
    nameAr: 'ضغط ثلاثي بالحبل',
    role: 'HYPERTROPHY_PRIMARY',
    orderClass: 'ACCESSORY',
    equipmentIds: ['cable'],
    primaryMuscleIds: ['triceps'],
    secondaryMuscleIds: [],
    requiresGym: true,
    canBeReplaced: false,
    defaultWarmupSeconds: 60,
    defaultWorkingSetSeconds: 40,
    transitionSeconds: 30
  },
  'standing-calf-raise': {
    id: 'standing-calf-raise',
    movementPatternId: 'CALF',
    name: 'Standing Calf Raise',
    nameAr: 'رفع سمانة واقف',
    role: 'HYPERTROPHY_PRIMARY',
    orderClass: 'ACCESSORY',
    equipmentIds: ['calf-machine'],
    primaryMuscleIds: ['calves'],
    secondaryMuscleIds: [],
    requiresGym: true,
    canBeReplaced: false,
    defaultWarmupSeconds: 60,
    defaultWorkingSetSeconds: 40,
    transitionSeconds: 30
  },
  'farmers-carry': {
    id: 'farmers-carry',
    movementPatternId: 'GRIP',
    name: 'Farmers Carry',
    nameAr: 'حمل المزارع',
    role: 'STRENGTH_AND_HYPERTROPHY',
    orderClass: 'ACCESSORY',
    equipmentIds: ['dumbbells'],
    primaryMuscleIds: ['grip'],
    secondaryMuscleIds: ['forearms'],
    requiresGym: true,
    canBeReplaced: false,
    defaultWarmupSeconds: 60,
    defaultWorkingSetSeconds: 30,
    transitionSeconds: 30
  },
  'box-jump': {
    id: 'box-jump',
    movementPatternId: 'LOWER_BODY_POWER',
    name: 'Box Jump',
    nameAr: 'قفز على صندوق',
    role: 'POWER_ONLY',
    orderClass: 'POWER',
    equipmentIds: ['box'],
    primaryMuscleIds: ['quadriceps'],
    secondaryMuscleIds: [],
    requiresGym: true,
    canBeReplaced: false,
    defaultWarmupSeconds: 120,
    defaultWorkingSetSeconds: 20,
    transitionSeconds: 90
  },
  // Day 2
  'trap-bar-deadlift': {
    id: 'trap-bar-deadlift',
    movementPatternId: 'HIP_HINGE',
    name: 'Trap-bar Deadlift',
    nameAr: 'رفعة ميتة ببار سداسي',
    role: 'STRENGTH_PRIMARY',
    orderClass: 'GYM_STRENGTH',
    equipmentIds: ['trap-bar', 'plates'],
    primaryMuscleIds: ['hamstrings'],
    secondaryMuscleIds: ['glutes'],
    requiresGym: true,
    canBeReplaced: true,
    defaultWarmupSeconds: 240,
    defaultWorkingSetSeconds: 60,
    transitionSeconds: 120
  },
  'overhead-press': {
    id: 'overhead-press',
    movementPatternId: 'VERTICAL_PUSH',
    name: 'Standing Overhead Press',
    nameAr: 'دفع كتف واقف',
    role: 'STRENGTH_AND_HYPERTROPHY',
    orderClass: 'GYM_STRENGTH',
    equipmentIds: ['barbell', 'plates'],
    primaryMuscleIds: ['anterior-deltoids'],
    secondaryMuscleIds: ['triceps'],
    requiresGym: true,
    canBeReplaced: true,
    defaultWarmupSeconds: 180,
    defaultWorkingSetSeconds: 60,
    transitionSeconds: 90
  },
  'chest-supported-row': {
    id: 'chest-supported-row',
    movementPatternId: 'HORIZONTAL_PULL',
    name: 'Chest-supported Row',
    nameAr: 'سحب مدعوم بالصدر',
    role: 'STRENGTH_AND_HYPERTROPHY',
    orderClass: 'GYM_STRENGTH',
    equipmentIds: ['bench', 'dumbbells'],
    primaryMuscleIds: ['upper-back'],
    secondaryMuscleIds: ['lats'],
    requiresGym: true,
    canBeReplaced: true,
    defaultWarmupSeconds: 120,
    defaultWorkingSetSeconds: 50,
    transitionSeconds: 75
  },
  'hack-squat': {
    id: 'hack-squat',
    movementPatternId: 'KNEE_DOMINANT',
    name: 'Hack Squat',
    nameAr: 'قرفصاء هاك',
    role: 'STRENGTH_AND_HYPERTROPHY',
    orderClass: 'GYM_HYPERTROPHY',
    equipmentIds: ['hack-squat'],
    primaryMuscleIds: ['quadriceps'],
    secondaryMuscleIds: [],
    requiresGym: true,
    canBeReplaced: false,
    defaultWarmupSeconds: 120,
    defaultWorkingSetSeconds: 50,
    transitionSeconds: 75
  },
  'lying-leg-curl': {
    id: 'lying-leg-curl',
    movementPatternId: 'KNEE_FLEXION',
    name: 'Lying Leg Curl',
    nameAr: 'ثني ركبة مستلق',
    role: 'HYPERTROPHY_PRIMARY',
    orderClass: 'GYM_HYPERTROPHY',
    equipmentIds: ['leg-curl'],
    primaryMuscleIds: ['hamstrings'],
    secondaryMuscleIds: [],
    requiresGym: true,
    canBeReplaced: true,
    defaultWarmupSeconds: 60,
    defaultWorkingSetSeconds: 40,
    transitionSeconds: 45
  },
  'ring-push-up': {
    id: 'ring-push-up',
    movementPatternId: 'HORIZONTAL_PUSH',
    name: 'Ring Push-up',
    nameAr: 'ضغط بالحلقات',
    role: 'STRENGTH_AND_HYPERTROPHY',
    orderClass: 'HYPERTROPHY_SKILL',
    equipmentIds: ['rings'],
    primaryMuscleIds: ['chest'],
    secondaryMuscleIds: ['triceps'],
    requiresGym: false,
    canBeReplaced: true,
    defaultWarmupSeconds: 120,
    defaultWorkingSetSeconds: 50,
    transitionSeconds: 75
  },
  'lat-pulldown': {
    id: 'lat-pulldown',
    movementPatternId: 'VERTICAL_PULL',
    name: 'Lat Pulldown',
    nameAr: 'سحب علوي',
    role: 'HYPERTROPHY_PRIMARY',
    orderClass: 'GYM_HYPERTROPHY',
    equipmentIds: ['cable'],
    primaryMuscleIds: ['lats'],
    secondaryMuscleIds: [],
    requiresGym: true,
    canBeReplaced: true,
    defaultWarmupSeconds: 120,
    defaultWorkingSetSeconds: 50,
    transitionSeconds: 60
  },
  'plate-pinch': {
    id: 'plate-pinch',
    movementPatternId: 'GRIP',
    name: 'Plate Pinch',
    nameAr: 'قرص القبضة',
    role: 'HYPERTROPHY_PRIMARY',
    orderClass: 'ACCESSORY',
    equipmentIds: ['plates'],
    primaryMuscleIds: ['grip'],
    secondaryMuscleIds: [],
    requiresGym: true,
    canBeReplaced: false,
    defaultWarmupSeconds: 60,
    defaultWorkingSetSeconds: 30,
    transitionSeconds: 30
  },
  'medicine-ball-throw': {
    id: 'medicine-ball-throw',
    movementPatternId: 'UPPER_BODY_POWER',
    name: 'Medicine-ball Chest Throw',
    nameAr: 'رمي كرة طبية',
    role: 'POWER_ONLY',
    orderClass: 'POWER',
    equipmentIds: ['medicine-ball'],
    primaryMuscleIds: ['chest'],
    secondaryMuscleIds: [],
    requiresGym: true,
    canBeReplaced: false,
    defaultWarmupSeconds: 120,
    defaultWorkingSetSeconds: 20,
    transitionSeconds: 60
  },
  // Day 3
  'front-squat': {
    id: 'front-squat',
    movementPatternId: 'KNEE_DOMINANT',
    name: 'Front Squat',
    nameAr: 'قرفصاء أمامية',
    role: 'STRENGTH_PRIMARY',
    orderClass: 'GYM_STRENGTH',
    equipmentIds: ['barbell', 'squat-rack', 'plates'],
    primaryMuscleIds: ['quadriceps'],
    secondaryMuscleIds: ['glutes'],
    requiresGym: true,
    canBeReplaced: true,
    defaultWarmupSeconds: 240,
    defaultWorkingSetSeconds: 60,
    transitionSeconds: 120
  },
  'low-incline-press': {
    id: 'low-incline-press',
    movementPatternId: 'HORIZONTAL_PUSH',
    name: 'Low-incline Bench Press',
    nameAr: 'ضغط مائل منخفض',
    role: 'STRENGTH_AND_HYPERTROPHY',
    orderClass: 'GYM_STRENGTH',
    equipmentIds: ['barbell', 'bench', 'plates'],
    primaryMuscleIds: ['chest'],
    secondaryMuscleIds: ['anterior-deltoids'],
    requiresGym: true,
    canBeReplaced: true,
    defaultWarmupSeconds: 180,
    defaultWorkingSetSeconds: 60,
    transitionSeconds: 90
  },
  'romanian-deadlift': {
    id: 'romanian-deadlift',
    movementPatternId: 'HIP_HINGE',
    name: 'Romanian Deadlift',
    nameAr: 'رفعة رومانية',
    role: 'STRENGTH_AND_HYPERTROPHY',
    orderClass: 'GYM_HYPERTROPHY',
    equipmentIds: ['barbell', 'plates'],
    primaryMuscleIds: ['hamstrings'],
    secondaryMuscleIds: ['glutes'],
    requiresGym: true,
    canBeReplaced: true,
    defaultWarmupSeconds: 120,
    defaultWorkingSetSeconds: 50,
    transitionSeconds: 75
  },
  'reverse-pec-deck': {
    id: 'reverse-pec-deck',
    movementPatternId: 'HORIZONTAL_PULL',
    name: 'Reverse Pec Deck',
    nameAr: 'بيك ديك عكسي',
    role: 'HYPERTROPHY_PRIMARY',
    orderClass: 'ACCESSORY',
    equipmentIds: ['cable'],
    primaryMuscleIds: ['rear-deltoids'],
    secondaryMuscleIds: [],
    requiresGym: true,
    canBeReplaced: false,
    defaultWarmupSeconds: 60,
    defaultWorkingSetSeconds: 40,
    transitionSeconds: 30
  },
  'leg-extension': {
    id: 'leg-extension',
    movementPatternId: 'KNEE_DOMINANT',
    name: 'Leg Extension',
    nameAr: 'بسط الركبة',
    role: 'HYPERTROPHY_PRIMARY',
    orderClass: 'ACCESSORY',
    equipmentIds: ['leg-extension'],
    primaryMuscleIds: ['quadriceps'],
    secondaryMuscleIds: [],
    requiresGym: true,
    canBeReplaced: false,
    defaultWarmupSeconds: 60,
    defaultWorkingSetSeconds: 40,
    transitionSeconds: 30
  },
  'reverse-curl': {
    id: 'reverse-curl',
    movementPatternId: 'GRIP',
    name: 'Reverse Curl',
    nameAr: 'كيرل عكسي',
    role: 'HYPERTROPHY_PRIMARY',
    orderClass: 'ACCESSORY',
    equipmentIds: ['barbell', 'plates'],
    primaryMuscleIds: ['brachialis'],
    secondaryMuscleIds: [],
    requiresGym: true,
    canBeReplaced: false,
    defaultWarmupSeconds: 60,
    defaultWorkingSetSeconds: 40,
    transitionSeconds: 30
  },
  'cable-triceps-pressdown': {
    id: 'cable-triceps-pressdown',
    movementPatternId: 'GRIP',
    name: 'Cable Triceps Pressdown',
    nameAr: 'ضغط ثلاثي بالكابل',
    role: 'HYPERTROPHY_PRIMARY',
    orderClass: 'ACCESSORY',
    equipmentIds: ['cable'],
    primaryMuscleIds: ['triceps'],
    secondaryMuscleIds: [],
    requiresGym: true,
    canBeReplaced: false,
    defaultWarmupSeconds: 60,
    defaultWorkingSetSeconds: 40,
    transitionSeconds: 30
  },
  'single-leg-calf-raise': {
    id: 'single-leg-calf-raise',
    movementPatternId: 'CALF',
    name: 'Single-leg Calf Raise',
    nameAr: 'رفع سمانة برجل واحدة',
    role: 'HYPERTROPHY_PRIMARY',
    orderClass: 'ACCESSORY',
    equipmentIds: ['box', 'plates', 'backpack'],
    primaryMuscleIds: ['calves'],
    secondaryMuscleIds: [],
    requiresGym: false,
    canBeReplaced: false,
    defaultWarmupSeconds: 60,
    defaultWorkingSetSeconds: 40,
    transitionSeconds: 30
  },
  'towel-dead-hang': {
    id: 'towel-dead-hang',
    movementPatternId: 'GRIP',
    name: 'Towel Dead Hang',
    nameAr: 'تعليق بالمنشفة',
    role: 'HYPERTROPHY_PRIMARY',
    orderClass: 'ACCESSORY',
    equipmentIds: ['pull-up-bar'],
    primaryMuscleIds: ['grip'],
    secondaryMuscleIds: ['forearms'],
    requiresGym: false,
    canBeReplaced: false,
    defaultWarmupSeconds: 60,
    defaultWorkingSetSeconds: 30,
    transitionSeconds: 30
  },
  'trap-bar-jump': {
    id: 'trap-bar-jump',
    movementPatternId: 'LOWER_BODY_POWER',
    name: 'Trap-bar Jump',
    nameAr: 'قفز بالبار السداسي',
    role: 'POWER_ONLY',
    orderClass: 'POWER',
    equipmentIds: ['trap-bar', 'plates'],
    primaryMuscleIds: ['quadriceps'],
    secondaryMuscleIds: [],
    requiresGym: true,
    canBeReplaced: false,
    defaultWarmupSeconds: 120,
    defaultWorkingSetSeconds: 20,
    transitionSeconds: 90
  }
};

export function getExerciseById(id: string): Exercise | undefined {
  return EXERCISE_CATALOG[id];
}

export function getExercisesByPattern(pattern: string): Exercise[] {
  return Object.values(EXERCISE_CATALOG).filter((e) => e.movementPatternId === pattern);
}
